#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require_relative "lexer"
  require_relative "../ast"

module GherkinRuby
  class Parser < Racc::Parser

module_eval(<<'...end gherkin.y/module_eval...', 'gherkin.y', 133)

  def parse(input)
    @yydebug = true if ENV['DEBUG_RACC']
    scan_str(input)
  end
...end gherkin.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    18,    18,    18,    18,    18,    20,    36,    37,    38,    39,
    40,    55,    18,    68,    57,    43,    57,     4,    18,    20,
    18,    21,    10,    72,    71,    36,    37,    38,    39,    40,
    18,    18,    14,    10,    45,    36,    37,    38,    39,    40,
    36,    37,    38,    39,    40,     4,     9,    14,    10,    10,
     4,     9,    14,    10,    14,    10,    24,    26,     4,    27,
    32,     4,    47,    18,    48,     4,     4,    51,    21,     4,
    18,     4,     4,     4,     4,    64,    18,    21,    18,    29,
    11,    69,     4,     4 ]

racc_action_check = [
    25,    46,    62,    61,    17,    17,    46,    46,    46,    46,
    46,    46,    70,    62,    46,    25,    61,    15,     5,     5,
    59,    15,     5,    70,    70,    59,    59,    59,    59,    59,
    44,    30,    16,    16,    30,    44,    44,    44,    44,    44,
    23,    23,    23,    23,    23,     0,     0,     2,     2,     0,
     3,     3,    31,    31,    12,    12,     7,     9,    29,    11,
    20,     8,    35,    41,    42,    43,    24,    45,     6,    48,
    49,    51,    52,    53,    55,    57,    58,    19,    60,    14,
     1,    63,    67,    34 ]

racc_action_pointer = [
    43,    80,    42,    48,   nil,    16,    62,    52,    59,    40,
   nil,    59,    49,   nil,    62,    15,    27,     2,   nil,    71,
    43,   nil,   nil,    33,    64,    -2,   nil,   nil,   nil,    56,
    29,    47,   nil,   nil,    81,    45,   nil,   nil,   nil,   nil,
   nil,    61,    47,    63,    28,    50,    -1,   nil,    67,    68,
   nil,    69,    70,    71,   nil,    72,   nil,    59,    74,    18,
    76,     1,     0,    65,   nil,   nil,   nil,    80,   nil,   nil,
    10,   nil,   nil ]

racc_action_default = [
   -47,   -47,    -1,   -47,    -5,   -47,    -7,    -9,   -11,   -47,
   -45,   -47,    -2,   -41,   -47,   -47,    -3,   -47,    -6,    -8,
   -47,   -46,   -10,   -47,   -47,   -12,   -14,    73,   -42,   -47,
   -47,    -4,   -15,   -18,   -20,   -47,   -28,   -29,   -30,   -31,
   -32,   -19,   -13,   -47,   -47,   -47,   -21,   -27,   -47,   -16,
   -43,   -47,   -22,   -24,   -26,   -47,   -36,   -47,   -17,   -47,
   -23,   -25,   -47,   -38,   -39,   -44,   -37,   -47,   -34,   -40,
   -47,   -33,   -35 ]

racc_goto_table = [
     5,    28,    33,    17,    56,     6,     2,    12,    25,    16,
    19,    23,    42,    22,    52,    30,    53,    67,     3,    66,
    28,    31,    63,    50,    41,    54,     1,   nil,   nil,    44,
   nil,   nil,   nil,   nil,    46,   nil,   nil,   nil,    65,   nil,
   nil,   nil,   nil,    49,   nil,   nil,   nil,   nil,    58,   nil,
   nil,    59,    60,    61,   nil,    62,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    70 ]

racc_goto_check = [
     5,    20,    12,     5,    18,     6,     2,     3,     5,     2,
     6,    11,    10,     8,    14,     5,    15,    17,     4,    18,
    20,     3,    19,    12,     5,    12,     1,   nil,   nil,     5,
   nil,   nil,   nil,   nil,     5,   nil,   nil,   nil,    12,   nil,
   nil,   nil,   nil,     5,   nil,   nil,   nil,   nil,     5,   nil,
   nil,     5,     5,     5,   nil,     5,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5 ]

racc_goto_pointer = [
   nil,    26,     6,     5,    18,     0,     5,   nil,     6,   nil,
   -13,     4,   -21,   nil,   -32,   -30,   nil,   -45,   -42,   -35,
   -11 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,    15,     7,   nil,     8,
   nil,   nil,   nil,    34,   nil,   nil,    35,   nil,   nil,   nil,
    13 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 19, :_reduce_1,
  2, 19, :_reduce_2,
  2, 19, :_reduce_3,
  3, 19, :_reduce_4,
  1, 23, :_reduce_none,
  2, 23, :_reduce_none,
  1, 22, :_reduce_7,
  2, 22, :_reduce_8,
  1, 20, :_reduce_9,
  2, 20, :_reduce_10,
  1, 25, :_reduce_11,
  2, 25, :_reduce_12,
  3, 25, :_reduce_13,
  2, 27, :_reduce_14,
  3, 27, :_reduce_15,
  2, 28, :_reduce_16,
  3, 28, :_reduce_17,
  2, 26, :_reduce_18,
  2, 29, :_reduce_19,
  1, 30, :_reduce_20,
  2, 30, :_reduce_21,
  3, 30, :_reduce_22,
  4, 30, :_reduce_23,
  3, 30, :_reduce_24,
  4, 30, :_reduce_25,
  3, 30, :_reduce_26,
  2, 31, :_reduce_27,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  5, 32, :_reduce_33,
  1, 35, :_reduce_34,
  3, 35, :_reduce_35,
  1, 33, :_reduce_36,
  3, 33, :_reduce_37,
  2, 36, :_reduce_38,
  1, 37, :_reduce_39,
  2, 37, :_reduce_40,
  1, 21, :_reduce_41,
  2, 21, :_reduce_42,
  4, 38, :_reduce_43,
  6, 38, :_reduce_44,
  1, 24, :_reduce_45,
  2, 24, :_reduce_46 ]

racc_reduce_n = 47

racc_shift_n = 73

racc_token_table = {
  false => 0,
  :error => 1,
  :NEWLINE => 2,
  :FEATURE => 3,
  :BACKGROUND => 4,
  :SCENARIO => 5,
  :TAG => 6,
  :GIVEN => 7,
  :WHEN => 8,
  :THEN => 9,
  :AND => 10,
  :BUT => 11,
  :DOC_STRING_START => 12,
  :DOC_STRING_LINE => 13,
  :DOC_STRING_END => 14,
  :TABLE_ROW_START => 15,
  :TABLE_CELL => 16,
  :TEXT => 17 }

racc_nt_base = 18

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "NEWLINE",
  "FEATURE",
  "BACKGROUND",
  "SCENARIO",
  "TAG",
  "GIVEN",
  "WHEN",
  "THEN",
  "AND",
  "BUT",
  "DOC_STRING_START",
  "DOC_STRING_LINE",
  "DOC_STRING_END",
  "TABLE_ROW_START",
  "TABLE_CELL",
  "TEXT",
  "$start",
  "Root",
  "Feature",
  "Scenarios",
  "FeatureTags",
  "Newline",
  "Tags",
  "FeatureHeader",
  "Background",
  "FeatureName",
  "Description",
  "BackgroundHeader",
  "Steps",
  "Step",
  "DocString",
  "Table",
  "Keyword",
  "DocStringLines",
  "TableRow",
  "TableCells",
  "Scenario" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'gherkin.y', 16)
  def _reduce_1(val, _values, result)
     result = val[0]; 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 19)
  def _reduce_2(val, _values, result)
     result = val[0]; result.scenarios = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 20)
  def _reduce_3(val, _values, result)
     result = val[1]; result.tags = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 22)
  def _reduce_4(val, _values, result)
     result = val[1]; result.scenarios = val[2]; result.tags = val[0] 
    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'gherkin.y', 31)
  def _reduce_7(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 32)
  def _reduce_8(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 35)
  def _reduce_9(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 37)
  def _reduce_10(val, _values, result)
     result = val[0]; result.background = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 41)
  def _reduce_11(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 42)
  def _reduce_12(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 44)
  def _reduce_13(val, _values, result)
     result = val[0]; result.description = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 48)
  def _reduce_14(val, _values, result)
     result = AST::Feature.new(val[1]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 49)
  def _reduce_15(val, _values, result)
     result = AST::Feature.new(val[2]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 53)
  def _reduce_16(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 54)
  def _reduce_17(val, _values, result)
     result = val[0...-1].flatten 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 59)
  def _reduce_18(val, _values, result)
     result = val[0]; result.steps = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 63)
  def _reduce_19(val, _values, result)
     result = AST::Background.new; result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 67)
  def _reduce_20(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 68)
  def _reduce_21(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 69)
  def _reduce_22(val, _values, result)
     val[0].doc_string = val[2]; result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 70)
  def _reduce_23(val, _values, result)
     val[0].doc_string = val[2]; result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 71)
  def _reduce_24(val, _values, result)
     val[0].table = val[2]; result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 72)
  def _reduce_25(val, _values, result)
     val[0].table = val[2]; result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 73)
  def _reduce_26(val, _values, result)
     val[2].unshift(val[0]); result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 77)
  def _reduce_27(val, _values, result)
     result = AST::Step.new(val[1], val[0]); result.pos(filename, lineno) 
    result
  end
.,.,

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

module_eval(<<'.,.,', 'gherkin.y', 85)
  def _reduce_33(val, _values, result)
     result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 89)
  def _reduce_34(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 90)
  def _reduce_35(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 94)
  def _reduce_36(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 95)
  def _reduce_37(val, _values, result)
     val[0] << val[2]; result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 99)
  def _reduce_38(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 103)
  def _reduce_39(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 104)
  def _reduce_40(val, _values, result)
     result = val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 108)
  def _reduce_41(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 109)
  def _reduce_42(val, _values, result)
     result = val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 114)
  def _reduce_43(val, _values, result)
     result = AST::Scenario.new(val[1], val[3]); result.pos(filename, lineno - 1) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 117)
  def _reduce_44(val, _values, result)
     result = AST::Scenario.new(val[3], val[5], val[0]); result.pos(filename, lineno - 2) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 121)
  def _reduce_45(val, _values, result)
     result = [AST::Tag.new(val[0])] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 122)
  def _reduce_46(val, _values, result)
     result = val[0] << AST::Tag.new(val[1]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module GherkinRuby
