#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require_relative "lexer"
  require_relative "../ast"

module GherkinRuby
  class Parser < Racc::Parser

module_eval(<<'...end gherkin.y/module_eval...', 'gherkin.y', 151)

  def parse(input)
    @yydebug = true if ENV['DEBUG_RACC']
    scan_str(input)
  end
...end gherkin.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    21,    21,    21,    21,    21,    21,    16,    18,    21,    10,
    40,    41,    42,    43,    44,    63,    65,    47,    65,    65,
    65,    88,    87,    21,    21,    21,    21,    23,    49,    50,
    21,    40,    41,    42,    43,    44,    81,    40,    41,    42,
    43,    44,    21,    16,    18,     4,    10,    21,    34,    40,
    41,    42,    43,    44,    40,    41,    42,    43,    44,    21,
    23,     4,     4,     9,     4,    10,    53,    24,    10,    40,
    41,    42,    43,    44,    16,    18,    21,    10,    16,    18,
    54,    10,     4,     9,    32,     4,    57,    58,    30,    29,
     4,     4,     4,     4,    70,     4,     4,     4,    75,    21,
     4,    27,     4,    21,    24,    36,    82,    70,    24,     4,
     4,    11,     4 ]

racc_action_check = [
    28,    78,    55,    52,    86,    72,     2,     2,    85,     2,
    52,    52,    52,    52,    52,    52,    78,    28,    52,    86,
    72,    85,    85,    73,    67,    33,    20,    20,    33,    33,
    48,    67,    67,    67,    67,    67,    73,    48,    48,    48,
    48,    48,    51,    19,    19,    34,    19,    68,    18,    51,
    51,    51,    51,    51,    68,    68,    68,    68,    68,     5,
     5,    17,     0,     0,    38,     5,    39,    17,     0,    26,
    26,    26,    26,    26,    35,    35,    45,    35,    12,    12,
    46,    12,     3,     3,    16,    27,    49,    50,    11,     9,
    54,    32,    57,    58,    59,    60,    61,    63,    65,    66,
     8,     7,    70,    71,     6,    23,    74,    77,    22,    80,
    84,     1,    47 ]

racc_action_pointer = [
    60,   111,     1,    80,   nil,    57,    96,    97,    98,    70,
   nil,    88,    73,   nil,   nil,   nil,    65,    59,    29,    38,
    24,   nil,   100,    86,   nil,   nil,    60,    83,    -2,   nil,
   nil,   nil,    89,    23,    43,    69,   nil,   nil,    62,    47,
   nil,   nil,   nil,   nil,   nil,    74,    61,   110,    28,    67,
    68,    40,     1,   nil,    88,     0,   nil,    90,    91,    87,
    93,    94,   nil,    95,   nil,    80,    97,    22,    45,   nil,
   100,   101,     3,    21,    88,   nil,   nil,   100,    -1,   nil,
   107,   nil,   nil,   nil,   108,     6,     2,   nil,   nil ]

racc_action_default = [
   -52,   -52,    -1,   -52,    -5,   -52,    -7,    -9,   -11,   -52,
   -50,   -52,    -2,   -41,   -43,   -44,   -52,   -52,   -52,    -3,
   -52,    -6,    -8,   -52,   -51,   -10,   -52,   -52,   -12,   -14,
    89,   -42,   -52,   -52,   -52,    -4,   -15,   -18,   -20,   -52,
   -28,   -29,   -30,   -31,   -32,   -19,   -13,   -52,   -52,   -52,
   -52,   -52,   -21,   -27,   -52,   -16,   -45,   -52,   -52,   -52,
   -22,   -24,   -26,   -52,   -36,   -52,   -17,   -52,   -52,   -47,
   -52,   -23,   -25,   -52,   -38,   -39,   -46,   -52,   -52,   -37,
   -52,   -34,   -40,   -48,   -52,   -52,   -49,   -33,   -35 ]

racc_goto_table = [
     5,    31,    61,    20,    37,    69,    79,     6,    28,    26,
     2,    60,    22,    19,    12,    46,    80,    33,    25,    74,
    79,     3,     1,    83,    31,   nil,    56,    45,    84,    59,
    62,    35,    48,   nil,    51,   nil,   nil,   nil,    52,   nil,
   nil,   nil,   nil,   nil,   nil,    76,    77,    55,   nil,   nil,
   nil,   nil,   nil,   nil,    66,   nil,   nil,    67,    68,   nil,
    71,    72,   nil,    73,   nil,   nil,   nil,   nil,   nil,   nil,
    78,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    85,   nil,   nil,   nil,    86 ]

racc_goto_check = [
     5,    20,    15,     5,    12,    23,    18,     6,     5,    11,
     2,    14,     6,     2,     3,    10,    17,     5,     8,    19,
    18,     4,     1,    23,    20,   nil,    12,     5,    15,    12,
    12,     3,     5,   nil,     5,   nil,   nil,   nil,     5,   nil,
   nil,   nil,   nil,   nil,   nil,    12,    12,     5,   nil,   nil,
   nil,   nil,   nil,   nil,     5,   nil,   nil,     5,     5,   nil,
     5,     5,   nil,     5,   nil,   nil,   nil,   nil,   nil,   nil,
     5,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     5,   nil,   nil,   nil,     5 ]

racc_goto_pointer = [
   nil,    22,    10,    12,    21,     0,     7,   nil,    11,   nil,
   -13,     2,   -22,   nil,   -41,   -50,   nil,   -57,   -66,   -46,
   -11,   nil,   nil,   -54 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,    17,     7,   nil,     8,
   nil,   nil,   nil,    38,   nil,   nil,    39,   nil,    64,   nil,
    13,    14,    15,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 21, :_reduce_1,
  2, 21, :_reduce_2,
  2, 21, :_reduce_3,
  3, 21, :_reduce_4,
  1, 25, :_reduce_none,
  2, 25, :_reduce_none,
  1, 24, :_reduce_7,
  2, 24, :_reduce_8,
  1, 22, :_reduce_9,
  2, 22, :_reduce_10,
  1, 27, :_reduce_11,
  2, 27, :_reduce_12,
  3, 27, :_reduce_13,
  2, 29, :_reduce_14,
  3, 29, :_reduce_15,
  2, 30, :_reduce_16,
  3, 30, :_reduce_17,
  2, 28, :_reduce_18,
  2, 31, :_reduce_19,
  1, 32, :_reduce_20,
  2, 32, :_reduce_21,
  3, 32, :_reduce_22,
  4, 32, :_reduce_23,
  3, 32, :_reduce_24,
  4, 32, :_reduce_25,
  3, 32, :_reduce_26,
  2, 33, :_reduce_27,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  5, 34, :_reduce_33,
  1, 37, :_reduce_34,
  3, 37, :_reduce_35,
  1, 35, :_reduce_36,
  3, 35, :_reduce_37,
  2, 38, :_reduce_38,
  1, 39, :_reduce_39,
  2, 39, :_reduce_40,
  1, 23, :_reduce_41,
  2, 23, :_reduce_42,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  4, 41, :_reduce_45,
  6, 41, :_reduce_46,
  5, 42, :_reduce_47,
  7, 42, :_reduce_48,
  4, 43, :_reduce_49,
  1, 26, :_reduce_50,
  2, 26, :_reduce_51 ]

racc_reduce_n = 52

racc_shift_n = 89

racc_token_table = {
  false => 0,
  :error => 1,
  :NEWLINE => 2,
  :FEATURE => 3,
  :BACKGROUND => 4,
  :SCENARIO => 5,
  :OUTLINE => 6,
  :EXAMPLES => 7,
  :TAG => 8,
  :GIVEN => 9,
  :WHEN => 10,
  :THEN => 11,
  :AND => 12,
  :BUT => 13,
  :DOC_STRING_START => 14,
  :DOC_STRING_LINE => 15,
  :DOC_STRING_END => 16,
  :TABLE_ROW_START => 17,
  :TABLE_CELL => 18,
  :TEXT => 19 }

racc_nt_base = 20

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "NEWLINE",
  "FEATURE",
  "BACKGROUND",
  "SCENARIO",
  "OUTLINE",
  "EXAMPLES",
  "TAG",
  "GIVEN",
  "WHEN",
  "THEN",
  "AND",
  "BUT",
  "DOC_STRING_START",
  "DOC_STRING_LINE",
  "DOC_STRING_END",
  "TABLE_ROW_START",
  "TABLE_CELL",
  "TEXT",
  "$start",
  "Root",
  "Feature",
  "Scenarios",
  "FeatureTags",
  "Newline",
  "Tags",
  "FeatureHeader",
  "Background",
  "FeatureName",
  "Description",
  "BackgroundHeader",
  "Steps",
  "Step",
  "DocString",
  "Table",
  "Keyword",
  "DocStringLines",
  "TableRow",
  "TableCells",
  "Scenario",
  "SimpleScenario",
  "ScenarioOutline",
  "Examples" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'gherkin.y', 16)
  def _reduce_1(val, _values, result)
     result = val[0]; 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 19)
  def _reduce_2(val, _values, result)
     result = val[0]; result.scenarios = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 20)
  def _reduce_3(val, _values, result)
     result = val[1]; result.tags = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 22)
  def _reduce_4(val, _values, result)
     result = val[1]; result.scenarios = val[2]; result.tags = val[0] 
    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'gherkin.y', 31)
  def _reduce_7(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 32)
  def _reduce_8(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 35)
  def _reduce_9(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 37)
  def _reduce_10(val, _values, result)
     result = val[0]; result.background = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 41)
  def _reduce_11(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 42)
  def _reduce_12(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 44)
  def _reduce_13(val, _values, result)
     result = val[0]; result.description = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 48)
  def _reduce_14(val, _values, result)
     result = AST::Feature.new(val[1]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 49)
  def _reduce_15(val, _values, result)
     result = AST::Feature.new(val[2]); result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 53)
  def _reduce_16(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 54)
  def _reduce_17(val, _values, result)
     result = val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 59)
  def _reduce_18(val, _values, result)
     result = val[0]; result.steps = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 63)
  def _reduce_19(val, _values, result)
     result = AST::Background.new; result.pos(filename, lineno) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 67)
  def _reduce_20(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 68)
  def _reduce_21(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 69)
  def _reduce_22(val, _values, result)
     val[0].doc_string = val[2]; result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 70)
  def _reduce_23(val, _values, result)
     val[0].doc_string = val[2]; result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 71)
  def _reduce_24(val, _values, result)
     val[0].table = val[2]; result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 72)
  def _reduce_25(val, _values, result)
     val[0].table = val[2]; result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 73)
  def _reduce_26(val, _values, result)
     val[2].unshift(val[0]); result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 77)
  def _reduce_27(val, _values, result)
     result = AST::Step.new(val[1], val[0]); result.pos(filename, lineno) 
    result
  end
.,.,

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

module_eval(<<'.,.,', 'gherkin.y', 85)
  def _reduce_33(val, _values, result)
     result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 89)
  def _reduce_34(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 90)
  def _reduce_35(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 94)
  def _reduce_36(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 95)
  def _reduce_37(val, _values, result)
     val[0] << val[2]; result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 99)
  def _reduce_38(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 103)
  def _reduce_39(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 104)
  def _reduce_40(val, _values, result)
     result = val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 108)
  def _reduce_41(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 109)
  def _reduce_42(val, _values, result)
     result = val[0] << val[1] 
    result
  end
.,.,

# reduce 43 omitted

# reduce 44 omitted

module_eval(<<'.,.,', 'gherkin.y', 119)
  def _reduce_45(val, _values, result)
     result = AST::Scenario.new(val[1], val[3]); result.pos(filename, lineno - 1) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 122)
  def _reduce_46(val, _values, result)
     result = AST::Scenario.new(val[3], val[5], val[0]); result.pos(filename, lineno - 2) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 127)
  def _reduce_47(val, _values, result)
     result = AST::ScenarioOutline.new(val[1], val[3], val[4]); result.pos(filename, lineno - 1) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 130)
  def _reduce_48(val, _values, result)
     result = AST::ScenarioOutline.new(val[3], val[5], val[6], val[0]); result.pos(filename, lineno - 2) 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 135)
  def _reduce_49(val, _values, result)
     result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 139)
  def _reduce_50(val, _values, result)
     result = [AST::Tag.new(val[0])] 
    result
  end
.,.,

module_eval(<<'.,.,', 'gherkin.y', 140)
  def _reduce_51(val, _values, result)
     result = val[0] << AST::Tag.new(val[1]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module GherkinRuby
